ApsisYönetim.Web/Controllers/ApartmentController.cs
using ApsisYönetim.Core.Entities;
using ApsisYönetim.Core.Interfaces.Services;
using ApsisYönetim.Service.DTOs.Apartment;
using ApsisYönetim.Service.DTOs.User;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApsisYönetim.Web.Controllers
{
    [Authorize(Roles = nameof(Roles.User) + "," + nameof(Roles.Admin))]
    public class ApartmentController : Controller
    {
        private readonly IApartmentService _apartmentService = null;
        private readonly IUserService _userService = null;
        private readonly IMapper _mapper = null;
        public ApartmentController(IApartmentService apartmentService, IUserService userService, IMapper mapper)
        {
            _apartmentService = apartmentService;
            _userService = userService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ShowApartments()
        {
            var res = await _apartmentService.GetAllApartmentsWithUsers();
            List<Apartment> apartments = res.Data;
            return View(_mapper.Map<List<ListApartWithUserEmailDto>>(apartments));

        }

        public async Task<IActionResult> Delete(int apartmentid)
        {

            var existApart = await _apartmentService.GetAsync(x => x.ID == apartmentid);
            var result = await _apartmentService.Delete(existApart.Data);

            if (result.Success)
            {
                return RedirectToAction("ShowApartments", "Apartment");
            }

            return NotFound();
        }

        public async Task<IActionResult> Edit(int apartmentid)
        {
            var res = await _apartmentService.GetApartmentWithUser(apartmentid);
            Apartment apartment = res.Data;
            

            List<User> users = _userService.GetAllAsync().Result.Data;
           
            ViewBag.Users = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(users, "Id", "Email");


            return View(_mapper.Map<EditApartmentDto>(apartment));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditApartmentDto apartDto)
        {

            Apartment updatedApart = _mapper.Map<Apartment>(apartDto);

            var res = await _apartmentService.Update(updatedApart);
            if (res.Success)
            {

                return RedirectToAction("ShowApartments");
            }

            return RedirectToAction("Edit");
        }


        public async Task<IActionResult> Create()
        {
            List<User> users = _userService.GetAllAsync().Result.Data;

            ViewBag.Users = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(users,"Id","Email");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddApartmentDto apartmentdto)
        {
            if (!ModelState.IsValid)
            {
                var messages = ModelState.ToList();

                return View(apartmentdto);

            }

            Apartment apartment = _mapper.Map<Apartment>(apartmentdto);
            User user = _userService.GetAsync(x => x.Id == apartmentdto.UserId).Result.Data;
            apartment.User = user;

            var result = await _apartmentService.AddAsync(apartment);

            if (result.Success)
            {
                return RedirectToAction("Index","Admin");
            }
            return View();
        }

        

        //public async Task<IActionResult> GetAllApertmentsWithUsers()
        //{
            
        //}

        public async Task<IActionResult> GetChargesWithApartments()
        {
            var user = await _userService.GetAsync(x => x.UserName == User.Identity.Name);

            //string useridfromsession = HttpContext.Session.GetString("userid");

            var result = await _apartmentService.GetApartmentsWithMonthlyCharge(user.Data.Id);
            List<Apartment> apartments = result.Data;
            List<ApartmentWithChargeDto> dto = new List<ApartmentWithChargeDto>();

            foreach (Apartment apart in apartments)
            {
                foreach (MonthlyCharge charge in apart.MonthlyCharge)
                {
                    dto.Add(new ApartmentWithChargeDto
                    {
                        IsPaid = charge.IsPaid,
                        MonthlyChargeID = charge.ID,
                        BlocNo = apart.BlocNo,
                        ElectricBill = charge.ElectricBill,
                        FloorNo = apart.FloorNo,
                        HeatingCost = charge.HeatingCost,
                        Subscription = charge.Subscription,
                        MonthOfPayment = charge.MonthOfPaymentAsString,
                    });
                }
            }


            return View(dto);
        }






    }
}

ApsisYönetim.Web/Controllers/PaymentController.cs
using ApsisYönetim.Core.Entities;
using ApsisYönetim.Core.Interfaces.Services;
using ApsisYönetim.Service.DTOs.CreditCard;
using ApsisYönetim.Service.Services.ApiCreditCardService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApsisYönetim.Web.Controllers
{
    [Authorize(Roles = nameof(Roles.User))]
    public class PaymentController : Controller
    {
        private readonly ICreditCardService _creditcardService = null;
        private readonly IMonthlyChargeService _monthlyChargeService = null;

        public PaymentController(ICreditCardService creditcardService, IMonthlyChargeService monthlyChargeService)
        {
            _creditcardService = creditcardService;
            _monthlyChargeService = monthlyChargeService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> PayCard(int chargeid)
        {
            var result = await _monthlyChargeService.GetAsync(x => x.ID == chargeid);
            MonthlyCharge charge = result.Data;

            //TempData["chargemoney"] = charge.TotalCharge;
            //TempData["chargeid"] = charge.ID ;

            CreditCardDto cardDto = new CreditCardDto { ChargeId = charge.ID, Money = charge.TotalCharge};


            return View(cardDto);

        } 
           

        [HttpPost]
        public async Task<IActionResult> PayCard(CreditCardDto cardDto)
        {

            if (!ModelState.IsValid)
            {
                var messages = ModelState.ToList();

                return View(cardDto);
            }

            var result = await _creditcardService.WithdrawMoney(cardDto);

            if (result.Success)
            {
                await _monthlyChargeService.SetPaid(cardDto.ChargeId);
                return RedirectToAction("Index", "User");
            }

            return View("ErrorDuringThePayment");
        }


        //public async Task<IActionResult> PayWithCreditCard(int chargeid)
        //{
        //    var result = await _monthlyChargeService.GetAsync(x => x.ID == chargeid);
        //    MonthlyCharge charge = result.Data;
        //    TempData["chargemoney"] = charge.TotalCharge;
        //    TempData["chargeid"] = chargeid;
        //    return View();
        //}

        //[HttpPost]
        //public async Task<IActionResult> PayWithCreditCard(CreditCardDto cardDto)
        //{
        //    cardDto.Money = (int)TempData["chargemoney"];
        //    int chargeid = (int)TempData["chargeid"];
        //    var result = await _creditcardService.WithdrawMoney(cardDto);

        //    if (result.Success)
        //    {
        //        await _monthlyChargeService.SetPaid(chargeid);
        //        return RedirectToAction("Index","User");
        //    }

        //    return View("ErrorDuringThePayment");
        //}

    }
}

ApsisYönetim.Web/Views/Apartment/Create.cshtml
@model AddApartmentDto

@{
    ViewData["Title"] = "Create";
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>


<h4>Apartman EKLE</h4>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.ApartType,"Apartman Tipi", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ApartType, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BlocNo, "Blok No ", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BlocNo, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FloorNo, "Kat No ",htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FloorNo, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    @*boolean*@
                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive,"Boş/Dolu",htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="custom-checkbox">
                            @Html.EditorFor(model => model.IsActive)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.UserId,"Ev sakini", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.UserId, ViewBag.Users as SelectList, "User seçiniz", htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>




                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-danger" />
                            @Html.ActionLink("Geri Dön","Index","Admin")
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ApsisYönetim.Web/Views/Apartment/Edit.cshtml
@model EditApartmentDto

@{
    ViewData["Title"] = "Edit";
}



<h4>Apartman Düzenle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BlocNo" class="control-label"></label>
                <input asp-for="BlocNo" class="form-control" />
                <span asp-validation-for="BlocNo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ApartType" class="control-label"></label>
                <input asp-for="ApartType" class="form-control" />
                <span asp-validation-for="ApartType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FloorNo" class="control-label"></label>
                <input asp-for="FloorNo" class="form-control" />
                <span asp-validation-for="FloorNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.UserId, "User ", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(model => model.UserId, ViewBag.Users as SelectList, "User seçiniz", htmlAttributes: new { @class = "form-control" })
            </div>
            @Html.HiddenFor(x=>x.ID)
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ApsisYönetim.Web/Views/Apartment/GetAllApertmentsWithUsers.cshtml
@model List<ListApartWithUserEmailDto>

@{
    ViewData["Title"] = "ListAllApartments";
}

<h1>Tüm Apartmanlar</h1>

<hr />
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Apartman Tipi</th>
            <th scope="col">Blok - No</th>
            <th scope="col">Kat - No</th>
            <th scope="col">Uygunluk Durumu</th>
            <th scope="col">Oturan Kişi Email</th>
            <th scope="col">Fatura</th>
            <th scope="col">Apartmanı Sil</th>
            <th scope="col">Düzenle</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var apartment in Model)
        {
            <tr>
                <th scope="row">@apartment.ID</th>
                <td>@apartment.ApartType</td>
                <td>@apartment.BlocNo</td>
                <td>@apartment.FloorNo</td>
                <td>@apartment.IsActive</td>
                <td>@apartment.Useremail</td>

                <td>@Html.ActionLink("Faturaları Göster", "", new { id = apartment.ID }) </td>
                <td>@Html.ActionLink("Apartmanı Sil", "", new { id = apartment.ID }) </td>
                <td>@Html.ActionLink("Düzenle", "", new { id = apartment.ID }) </td>

            </tr>


        }



    </tbody>
</table>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ApsisYönetim.Web/Views/Apartment/GetChargesWithApartments.cshtml
@model List<ApartmentWithChargeDto>
@{
    Layout = "~/Views/User/_UserLayout.cshtml";
}

<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Bloc NO</th>
            <th scope="col">Floor NO</th>
            <th scope="col">Elektrik Faturası</th>
            <th scope="col">Sıcak su ve Isıtma Faturası</th>
            <th scope="col">Aidat</th>
            <th scope="col">Toplam</th>
            <th scope="col">Ay</th>
            <th scope="col">Ödeme</th>


        </tr>
    </thead>
    <tbody>

        @foreach (var charge in Model)
        {
        <tr>
            <th scope="row"></th>
            <td>@charge.BlocNo</td>
            <td>@charge.FloorNo</td>
            <td>@charge.ElectricBill</td>
            <td>@charge.HeatingCost</td>
            <td>@charge.Subscription</td>
            <td>@charge.TotalCharge</td>
            <td>@charge.MonthOfPayment</td>
            @{
                if (!charge.IsPaid)
                {
                    <td>@Html.ActionLink("Kredi kartı ile öde", "PayCard", "Payment", new { chargeid = charge.MonthlyChargeID }) </td>
                }
                else
                {
                    <td>ÖDENMİŞTİR !</td>
                }
            }



        </tr>


        }



    </tbody>
</table>

ApsisYönetim.Web/Views/Apartment/ShowApartments.cshtml
@model List<ListApartWithUserEmailDto>

@{
    ViewData["Title"] = "ShowApartments";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h1>Apartmanlar</h1>

<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Blok-No</th>
            <th scope="col">Daire Tipi</th>
            <th scope="col">Kat-No</th>
            <th scope="col">Dolu/Boş</th>
            <th scope="col">Ev sakini Email</th>

        </tr>
    </thead>
    <tbody>
        @foreach (ListApartWithUserEmailDto apart in Model)
        {
            <tr>
                <th scope="row"></th>
                <td>@apart.BlocNo</td>
                <td>@apart.ApartType</td>
                <td>@apart.FloorNo</td>
                @if (apart.IsActive)
                {
                    <td>Dolu</td>
                }
                else
                {
                    <td>Boş</td>
                }

                <td>
                    @{
                        string emailOfUser = null;
                        if (apart.Useremail == null)
                        {
                            emailOfUser = "Kullanıcı yok";
                        }
                        else
                        {
                            emailOfUser = apart.Useremail;
                        }
                    }
                    @emailOfUser

                </td>

                <td>@Html.ActionLink("Düzenle", "Edit", "Apartment", new { apartmentid = apart.ID }) </td>
                <td>@Html.ActionLink("Sil", "Delete", "Apartment", new { apartmentid = apart.ID }) </td>
            </tr>


        }



    </tbody>
</table>