ApsisYönetim.Web/Controllers/MonthlyChargeController.cs
using ApsisYönetim.Core.Entities;
using ApsisYönetim.Core.Interfaces.Services;
using ApsisYönetim.Service.DTOs.Apartment;
using ApsisYönetim.Service.DTOs.MonthlyCharge;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApsisYönetim.Web.Controllers
{
    public class MonthlyChargeController : Controller
    {
        private readonly IApartmentService _apartmentService = null;
        private readonly IMonthlyChargeService _monthlyChargeService = null;
        private readonly IMapper _mapper = null;
        public MonthlyChargeController(IApartmentService apartmentService, IMonthlyChargeService monthlyChargeService,IMapper mapper)
        {
            _apartmentService = apartmentService;
            _monthlyChargeService = monthlyChargeService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddtoApartment()
        {
            List<Apartment> apartments = _apartmentService.GetAllAsync().Result.Data;
            var mappedaparts = _mapper.Map<List<AddChargeToApartDto>>(apartments);

            ViewBag.apartments = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(mappedaparts, "ID", "Info");

            
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> AddtoApartment(AddMonthlyChargeDto chargedto)
        {
            if(!ModelState.IsValid)
            {
                var messages = ModelState.ToList();

                return View(chargedto);

            }

            MonthlyCharge monthlyCharge = _mapper.Map<MonthlyCharge>(chargedto);

            var result = await _monthlyChargeService.AddAsync(monthlyCharge);

            if (result.Success)
            {
                return RedirectToAction("Index", "Admin");
            }

            return RedirectToAction("AddtoApartment");
        }



        public IActionResult SelectMonth()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SelectMonth(MonthofPaymentDto month)
        {
            var result = await _monthlyChargeService.GetAllMonthlyChargesByMonth((Months)month.MonthOfPayment);
            List<MonthlyCharge> charges = result.Data;
            var dtoResult = _mapper.Map<List<ShowChargesByMonthDto>>(charges);



            return View("ShowChargesByMonth",dtoResult);
        }

        public IActionResult ShowChargesByMonth(List<ShowChargesByMonthDto> chargesDto)
        {
            return View(chargesDto);
        }


    }
}

ApsisYönetim.Web/Controllers/NoteController.cs
using ApsisYönetim.Core.Entities;
using ApsisYönetim.Core.Interfaces.Services;
using ApsisYönetim.Service.DTOs.Note;
using ApsisYönetim.Web.AdminConfig;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApsisYönetim.Web.Controllers
{
    
    public class NoteController : Controller
    {
        private readonly INoteService _noteService = null;
        private readonly IMapper _mapper = null;
        private readonly IAdminEmail _adminEmail = null;

        public NoteController(IAdminEmail adminEmail,INoteService noteService, IMapper mapper)
        {
            _noteService = noteService;
            _mapper = mapper;
            _adminEmail = adminEmail;
        }

        [Authorize(Roles = nameof(Roles.Admin))]
        public async Task<IActionResult> ShowMessagesHaveAdmin()
        {
            string email = _adminEmail.Email;
            var result = await _noteService.GetAllAsync(x => x.Receiver == email);
            List<Note> notes = result.Data;
            List<ShowNotesDto> notesDto = _mapper.Map<List<ShowNotesDto>>(notes); 


            return View(notesDto);
        }

        [Authorize(Roles = nameof(Roles.User))]
        public IActionResult AddNoteToAdmin()
        {
            return View();
        }

        [Authorize(Roles = nameof(Roles.User))]
        [HttpPost]
        public async Task<IActionResult> AddNoteToAdmin(AddNoteDto noteDto)
        {

            if (!ModelState.IsValid)
            {
                var messages = ModelState.ToList();

                return View(noteDto);

            }
            Note note = _mapper.Map<Note>(noteDto);

            string userEmail = HttpContext.Session.GetString("email");
            note.Sender = userEmail;
            note.Receiver = _adminEmail.Email;


            var result = await _noteService.AddAsync(note);

            if (result.Success)
            {
                return RedirectToAction("Index", "User");
            }

            return RedirectToAction("AddNoteToAdmin");
        }
    }
}

ApsisYönetim.Web/Views/Admin/DetailUser.cshtml
@model ApsisYönetim.Service.DTOs.User.EditUserDto

@{
    ViewData["Title"] = "DetailUser";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";

}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

<h1>Kullanıcılar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DetailUser" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TcNo"  class="control-label"></label>
                <input asp-for="TcNo" class="form-control" />
                <span asp-validation-for="TcNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlakaNo" class="control-label"></label>
                <input asp-for="PlakaNo" class="form-control" />
                <span asp-validation-for="PlakaNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            @Html.HiddenFor(x => x.Id)
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ApsisYönetim.Web/Views/Admin/Index.cshtml
@{ 
    ViewData["Title"] = "Index";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

ApsisYönetim.Web/Views/Admin/ShowUser.cshtml
@model List<ListingUserDto>

@{
    ViewData["Title"] = "ShowUser";

}

<h1>Kullanıcılar</h1>

<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Tc-No</th>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">Plaka-No</th>
            <th scope="col">Phone-Number</th>
            <th scope="col">Apartments</th>
            <th scope="col">Detail</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <th scope="row"></th>
                <td>@user.TcNo</td>
                <td>@user.Username</td>
                <td>@user.Email</td>
                <td>@user.Name</td>
                <td>@user.Surname</td>
                <td>@user.PlakaNo</td>
                <td>@user.PhoneNumber</td>
                @{
                    string apartments = null;
                    foreach (var item in user.UsersApartments)
                    {
                        apartments += item +" " ;
                    }
                }
                @if (apartments == null)
                {
                    <td>--</td>
                }
                else
                {
                    <td>@apartments</td>
                }
                <td>@Html.ActionLink("Detay", "DetailUser", new { userid = user.Id }) </td>
                <td>@Html.ActionLink("Sil", "DeleteUser", new { userid = user.Id }) </td>
            </tr>


        }



    </tbody>
</table>

@Html.ActionLink("Anasayfa","Index","Admin")

@*<div>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        <a asp-action="Index">Back to List</a>
    </div>*@

ApsisYönetim.Web/Views/Admin/UserNotUpdated.cshtml
@{ 

    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h1>Kullanıcı güncellenemedi !!! </h1>

@Html.ActionLink("Kullanıcıları göster","ShowUser","Admin")

ApsisYönetim.Web/Views/Admin/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApsisYönetim.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    @Html.ActionLink("ApsisYönetim", "Index", "Home")
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @Html.ActionLink("Anasayfa", "Index", "Home", new { @class = "nav-link text-dark" })
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:10px">
            <div class="row">
                <div class="col-md-8">
                    @RenderBody()
                </div>
                <div class="col-md-4">
                    <h3>Admin Menü</h3>
                    @*TODO : Complete the link url *@
                    @*htmlAttributes: new { @class = "control-label col-md-2" }*@

                    @Html.ActionLink("Yeni Kullanıcı Gir", "CreateUser", "User", null, htmlAttributes: new { @class = "btn btn-info btn-block" })
                    @Html.ActionLink("Kullanıcıları Göster", "ShowUser", "Admin", null, htmlAttributes: new { @class = "btn btn-info btn-block" })
                    @Html.ActionLink("Fatura Gir", "AddtoApartment", "MonthlyCharge", null, htmlAttributes: new { @class = "btn btn-info btn-block" })
                    @Html.ActionLink("Yeni Apartman Gir", "Create", "Apartment", null, htmlAttributes: new { @class = "btn btn-info btn-block" })
                    @Html.ActionLink("Apartmanları Göster", "ShowApartments", "Apartment", null, htmlAttributes: new { @class = "btn btn-info btn-block" })
                    @Html.ActionLink("Mesaj Kutusu", "ShowMessagesHaveAdmin", "Note", null, htmlAttributes: new { @class = "btn btn-info btn-block" })
                    @Html.ActionLink("Aylık Borç Göster","SelectMonth", "MonthlyCharge", null, htmlAttributes: new { @class = "btn btn-info btn-block" })


                </div>
            </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ApsisYönetim - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>